### ISSUE TITLE
Subtitles not showing.

### ISSUE THREAD

**Issue by RohanTrix** [benzac-de/msx-interaction-plugin-examples#11]
I have setup MSX on Samsung Tizen using http-server. I have mkv file which has subtitles attacked to it(no external file). I can see the subtitle options on MSX but on selecting them, they are not being displayed. They do work on VLC on my laptop.

Please help me fix this.

**Comment by benzac-de** [comment]
Thank you for your comment.
Please try to enable subtitles in the Samsung TV settings.
If this does not help, please try to unplug external HDMI devices (some Samsung TVs do not show subtitles when external HDMI devices are connected).

**Comment by benzac-de** [comment]
Please note that in the upcoming version 0.1.145 the subtitle support for the Tizen player has been extended with in-app subtitles (which work independently of the TV settings and/or connected devices). This should fix common subtitle issues on Samsung TVs.
