### ISSUE TITLE
Media Station X showcases

### ISSUE THREAD

**Issue by SingingDwarf** [benzac-de/msx-interaction-plugin-examples#12]
Would you consider releasing the source for any of the showcases, such as The Movie DB showcase?

I would like to build a front-end to MythTV using MSX, but not sure where to start when accessing an external API.

**Comment by benzac-de** [comment]
Thank you for your comment.

I am already planning to create more MSX examples as open source projects that also include connections to 3rd party services.

For now, if you plan to integrate The Movie Database, please have a look at this API documentation: https://www.themoviedb.org/documentation/api
