### ISSUE TITLE
start parameter error

### ISSUE THREAD

**Issue by osmancitci** [benzac-de/msx-interaction-plugin-examples#9]
Hello Whatever I did in the web environment, I could not make it function. but it works on my TV but neither the phone nor the web work. I keep getting this error. **start parameter error server responded with status 0**

**Comment by benzac-de** [comment]
Thank you for your message. 
If you are getting this error on mobile but not on TV devices, the CORS headers are probably missing or incorrect (some older TV devices ignore CORS headers and allow any content).
For more information about this error, please see following link: https://msx.benzac.de/wiki/index.php?title=Tips_%26_Tricks#Common_Errors
